### ISSUE TITLE
issue with bower install

### ISSUE THREAD

**Issue by trucker-hub** [samwiseduzer/angularPrint#5]
$ bower install angular-print --save
bower angular-print#\*           cached git://github.com/samwiseduzer/angularPrint.git#0.3.7
bower angular-print#\*         validate 0.3.7 against git://github.com/samwiseduzer/angularPrint.git#*
bower angularPrint#~0.3.7    ENOTFOUND Package angularPrint not found

Could you take a look into this issue?

The issue caused some downstream issues when we want to manage the version.

Thanks,

-Jinbo

**Comment by samwiseduzer** [comment]
I'll take a look at that today and get back to you

**Comment by samwiseduzer** [comment]
this should be fixed this weekend. Thanks for your patience!

**Comment by trucker-hub** [comment]
Thanks!

On Thu, Oct 15, 2015 at 2:04 PM, samwiseduzer notifications@github.com
wrote:

> this should be fixed this weekend. Thanks for your patience!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samwiseduzer/angularPrint/issues/5#issuecomment-148520849
> .

## 

Jinbo Chen

**Comment by samwiseduzer** [comment]
I think the issue was with me not bumping the bower version with the last changes to the readme, so I reverted and then re-pushed with a bumped bower version. Let me know if this works.

**Comment by trucker-hub** [comment]
Sam,

Seems it does not fix the issue. Please see the console output.

bower install angular-print --save
bower angular-print#\*           cached git://github.com/samwiseduzer/angularPrint.git#0.3.8
bower angular-print#\*         validate 0.3.8 against git://github.com/samwiseduzer/angularPrint.git#*
bower angularPrint#0.3.8     ENOTFOUND Package angularPrint not found

**Comment by jmijmi** [comment]
This issue should be closed i just installled successfully using bower! :+1:

**Comment by samwiseduzer** [comment]
@trucker-hub I've tried several ways and have been unable to repro your issue. I don't want to close it, since something must be wrong. However, could you tell me what version of bower you're running? And are you having trouble with any other bower packages?

**Comment by samwiseduzer** [comment]
have you tried removing and reinstalling the package?

**Comment by trucker-hub** [comment]
it's good now. You can close it. 

Thanks

-Jinbo

**Comment by samwiseduzer** [comment]
thanks for getting back to me!
